apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-listener
  namespace: workflows-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-listener
  template:
    metadata:
      labels:
        app: event-listener
    spec:
      serviceAccountName: event-listener
      containers:
      - name: event-listener
        image: ko://github.com/nubank/workflows/cmd/event-listener
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 512Mi
        ports:
        - name: event-listener
          containerPort: 8080
#        livenessProbe:
#          httpGet:
#            path: /live
#            port: 8080
#          initialDelaySeconds: 10
#          periodSeconds: 3
        env:
        - name: LOGGER_CONFIG
          valueFrom:
            configMapKeyRef:
              name: config-logging
              key: zap-logger-config
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: config-logging
              key: loglevel.eventlistener
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
