apiVersion: apps/v1
kind: Deployment
metadata:
  name: hook-listener
  namespace: workflows-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hook-listener
  template:
    metadata:
      labels:
        app: hook-listener
    spec:
      serviceAccountName: hook-listener
      containers:
      - name: hook-listener
        image: ko://github.com/nubank/workflows/cmd/hook-listener
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 512Mi
        ports:
        - name: hook-listener
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 60
        env:
        - name: LOGGER_CONFIG
          valueFrom:
            configMapKeyRef:
              name: config-logging
              key: zap-logger-config
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: config-logging
              key: loglevel.hooklistener
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
