apiVersion: v1
kind: ConfigMap
metadata:
  name: config-github-app
  namespace: workflows-system
  labels:
    workflows.workflows.dev/release: devel
data:
  app-id: "99958"
  installation-id: "14656263"
