apiVersion: workflows.dev/v1alpha1
kind: Workflow
metadata:
  name: hello-world
spec:
  repo:
    name: dummy-clj-lib
    owner: alan-ghelardi
  webhook:
    url: https://hooks.example.com

  on:
      - push

  tasks:
    hello-world:
      steps:
        - uses: checkout
        - run: pwd && ls -a
