apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.workflows.dev
  labels:
    knative.dev/crd-install: "true"
spec:
  group: workflows.dev
  version: v1alpha1
  names:
    kind: Workflow
    plural: workflows
    singular: workflow
    categories:
    - all
    - knative
    shortNames:
    - wf
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Ready
    type: string
    JSONPath: ".status.conditions[?(@.type=='Ready')].status"
  - name: Reason
    type: string
    JSONPath: ".status.conditions[?(@.type=='Ready')].reason"
